#Replace pneumatika with the name of your project
#Replace /pneumatika with the path to your project
#Replace 8000 with the port you want to use
#Replace root with the password you want to use
#Replace pneumatika with the name of your database
#Replace 3306 with the port you want to use for the database
#Change the container name to the name of your choice
services:
  #App Server
  laravel-docker-app:
    container_name: laravel-pneumatika
    build: .

    volumes:
      - /pneumatika:/var/www/html
    ports:
      - "8000:80"

  #Database
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pneumatika
    ports:
      - "3306:3306"
  #phpMyAdmin Server
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
